os: linux
language: python
python: 3.8
cache: pip
install: pip install -e .[dev]
script: flake8
before_deploy: python setup.py bdist_wheel
deploy:
  provider: pypi
  distributions: bdist_wheel
  on:
    tags: true
  username: tiborhari
  password:
    secure: s40n3JO4qvVKeQpme2dEzU+BpdRqPL/U/I94K1cuGc6Yy1wQeSpmF2aPJHUVgYjhLAViF+0krmcHdIPueGygh/e+tEqXnXBw8xJC9vFCF8RL3BPg47pTo591LoM9E5x5Y4PVg8U3+UiM1s3ZRqXN7GPdQXCQs8UNapsssI2169TRrIUFTDR0sBxzhZd6nuYiHrAa2ijZfDcZ9TQSgPebVDoCwpkrUY92AcH5tWZq39o9TyUQWL5kUtZsdeCtTZrdBu+JOQ28zeUUvjoF33oH+hqb22n7XCmX5f8VJXB5dlKRZPUr0fBrjlUExg28KE930C7Xzgd2OOlWbR9S7Gvp7chVNIwyrKvV/qWRGNvJto2nHFsO3b+7Pm4se//Rdk6bZ9EGAkk3LjDgz6aVe16pX5EDJXGc6E01QSRWGCLBLnOckPYeOornerVwYefVQYfybNw77yS63od8zOEXsTnKPnTFUp4MsREpjORxPJs8O4ayU/V40gPWeG8i5p6gAU6xgxR+WBHuEtXdsiWGX6PnouF8gzeQj1EriZWz4PA7q7ABXn8CcDDOtXyp80k+ABn4D/5itT8hPTQmUQrAQbqhcyyvb4cxBrkahT1RBGMg1Uf+MYeUVaEMH/v2juH6hK7tGXBBe5bXEP8BNnRDPxzzxHNXmmfg1kFQ6vKNWzh/S6g=
